// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvnzrypofceybqjatfrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12bnpyeXBvZmNleWJxamF0ZnJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTcwMzcsImV4cCI6MjA3MjA3MzAzN30.8EDQSVKhammkjw48XAbrL6ognf0vdmZaFTYEOhYRu6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});